-- UPDATE script: fix text and elevation defects in the Volcano dataset
-- Every defect below is carried over verbatim from the SGC feed the dataset was
-- seeded from (https://archive.sgc.gov.co/volcanos/volcanos.json); the feed itself
-- is the source of the truncation and of the spelling errors.
-- Idempotent: each UPDATE sets the final text in full and is keyed on "Name"
-- (unique), so re-running is a no-op (no INSERT, no duplicate-key risk).
-- Scope: clear orthographic/grammatical errors, one truncated description and one
--   elevation. Geological terminology and the SGC's own wording are left as-is.
-- These same corrections are already folded into scripts/Volcano_Data.sql, so a
-- fresh seed does not need this script; it exists for databases seeded earlier.

BEGIN;

-- Id 1 · Campo volcánico Guamuez-Sibundoy
UPDATE "Volcano" SET "Description" = 'El Campo volcánico monogenético Guamuez-Sibundoy se localiza a 20 km al oriente de la ciudad de Pasto (Nariño) y a 29,6 km al occidente del municipio de Santiago (Putumayo), en el corregimiento del Encano, municipio de Pasto, en las coordenadas geográficas 1°06′ N - 77°09′ W. El acceso a las estructuras que conforman este campo se realiza por la vía principal que comunica Pasto, capital de Nariño, con el departamento del Putumayo (ruta nacional 10), la cual transita por el corregimiento del Encano; de allí se toma una vía secundaria que lleva a un importante centro turístico, el cual tiene un puerto fluvial donde parten pequeños botes que la navegan. Esta es una de las formas de transporte para acceder a los edificios volcánicos que se ubican en el lado oriental de la laguna de La Cocha. Otra vía de acceso a los volcanes, es por medio de un camino que comunica las veredas del sector oriental de la laguna. Para acceder a los volcanes del Alto Putumayo se continúa por la ruta nacional 10 hasta el municipio de Santiago y de allí se toma una vía secundaria hasta la vereda Muchivioy, sector de asentamiento de la comunidad Inga Manoy' WHERE "Name" = 'Campo volcánico Guamuez-Sibundoy';

-- Id 2 · Complejo Volcánico Chiles-Cerro Negro
--   Elevation 4470 -> 4748 (cima del Chiles, punto más alto del complejo)
UPDATE "Volcano" SET "Description" = 'El Complejo Volcánico Chiles-Cerro Negro se edifica en intersecciones de la falla Chiles-Cerro Negro, con las fallas Chiles-Cumbal y Cerro Negro-Nasate, sobre un basamento representado por una secuencia potente de lavas pliocénicas, depositadas sobre rocas volcanosedimentarias de la formación Nariño, a su vez, depositadas sobre rocas de los grupos Dagua y Diabásico, así como sobre metamorfitas del grupo Cajamarca. El edificio actual del Chiles está conformado fundamentalmente por varios episodios de flujos de lava y el volcán Cerro Negro por flujos de lava y de piroclastos. De acuerdo con análisis químicos y petrográficos, los productos del Complejo Volcánico Chiles-Cerro Negro se clasifican como andesitas de dos piroxenos y olivinos. Se trata de dos conos volcánicos contiguos, el Chiles al extremo ESE y el Cerro Negro al WNW, colapsados hacia el N y W, con geoformas resultado de acción glaciar ya extinta. Las cimas volcánicas alcanzan las cotas de 4748 msnm (Chiles) y 4470 msnm (Cerro Negro), y sus cráteres tienen diámetros de 1,0 y 1,8 km, respectivamente. El complejo se ubica en la frontera entre Colombia y Ecuador, en inmediaciones de la inspección de policía de Chiles, municipio de Cumbal, a 86 km al suroccidente de Pasto.', "Elevation" = 4748 WHERE "Name" = 'Complejo Volcánico Chiles-Cerro Negro';

-- Id 3 · Volcán Azufral
UPDATE "Volcano" SET "Description" = 'El volcán Azufral es un estrato-volcán, con un diámetro del cráter estimado en 3 km, en donde se encuentra la laguna cratérica llamada Laguna Verde, no registra la presencia de glaciares, y presenta el registro de depósitos asociados con flujos de lava, flujos piroclásticos de gran magnitud y depósitos de caída (cenizas y pumitas). En la actualidad existe actividad fumarólica y algunas manifestaciones sísmicas. Se dispone de algunos registros sísmicos de eventos de Largo-periodo y algunas señales Volcano-tectónicas. Debido a la existencia de páramos en la cima se propicia condiciones para el nacimiento de fuentes de agua que esencialmente exhiben un patrón radial de drenaje' WHERE "Name" = 'Volcán Azufral';

-- Id 8 · Volcán Doña Juana
UPDATE "Volcano" SET "Description" = 'El Volcán Doña Juana localizado en el nor-oriente del Departamento de Nariño, es considerado como uno de los volcanes activos y peligrosos de Colombia; su registro de actividad histórica nos remonta al período 1897-1936, con la ocurrencia de varias erupciones explosivas que infortunadamente causaron la muerte de más de 100 personas y grandes pérdidas económicas en su región de influencia. El volcán Doña Juana es considerado como un estrato volcán andesítico, con un diámetro del cráter cercano a 4 km, sin glaciares, con registro de depósitos asociados con flujos de lava, flujos piroclásticos y cenizas; los riesgos que la actividad de este volcán pueden acarrear se relacionan con ocurrencia de flujos piroclásticos, flujos de lodo o lahares y caídas de ceniza. El 20 de junio de 2008 se instaló una estación sísmica denominada Lavas, dotada de un sensor triaxial de corto periodo, en un punto distante 4 km al sur-occidente de la cima volcánica. Para que las señales captadas por esta estación lleguen en tiempo real a la sede del Observatorio Vulcanológico y Sismológico de Pasto (OVSP) para su procesamiento y análisis, se cuenta con dos puntos de repetición, de manera que la señal que sale de la estación Lavas pasa por las repetidoras de Morasurco y Cruz de Amarillo antes de llegar al OVSP. En la región de influencia de Doña Juana, Ánimas y Petacas, se localizan varios municipios entre los que se mencionan a La Cruz, San Pablo, Belén, San Bernardo, San José. En siglos pasados, estas poblaciones correspondían a pequeños caseríos; sin embargo, con el tiempo se ha ido incrementado el número de habitantes así como la cantidad de poblaciones asentadas en sus faldas.' WHERE "Name" = 'Volcán Doña Juana';

-- Id 10 · Volcán Galeras
UPDATE "Volcano" SET "Description" = 'El volcán Galeras se localiza en el Departamento de Nariño, aproximadamente a 9 km al occidente de la Ciudad de San Juan de Pasto, capital de este departamento, en las coordenadas 1° 13'' 43,8" de latitud norte y 77° 21'' 33,0" de longitud oeste y con una altura de 4276 msnm. De acuerdo con el Catálogo de Volcanes Activos del Mundo (CAVW) de la Asociación Internacional de Vulcanología y Química del Interior de la Tierra (IAVCEI), su código es el 1501-08. Los indígenas Quillacingas dieron el nombre de "Urcunina" (Montaña de Fuego) al volcán de Pasto, hoy conocido "volcán Galeras"; llamado así, por los primeros conquistadores españoles, por su semejanza con las Galeras o barcos que con sus velas navegaban en aquel entonces por el Mediterráneo. Para su acceso tiene una carretera de unos 23 km en regular estado, que va de la ciudad de San Juan de Pasto (sector de Anganoy) hasta la cima y una vía circunvalar de aproximadamente 117,5 km, parcialmente pavimentada que lo rodea en su totalidad comunicando a San Juan de Pasto con los pueblos de Catambuco, Yacuanquer, Consacá, Sandoná, La Florida, Nariño y Genoy, en sentido horario. Adicionalmente, se cuenta con un camino no transitable vehicularmente llamado el Camino Real que une a San Juan de Pasto con Consacá, población localizada en el extremo opuesto al occidente del volcán, camino que atraviesa a media falda la montaña por el costado norte.' WHERE "Name" = 'Volcán Galeras';

-- Id 12 · Volcán Las Ánimas
UPDATE "Volcano" SET "Description" = 'Las Ánimas se encuentra situado al suroccidente del país, se emplaza en el Macizo Colombiano, en el departamento de Nariño, más exactamente en límites con el departamento del Cauca. Con una altura de 4200 msnm, Las Ánimas se localiza a unos 11 km al noreste del volcán Doña Juana y a 12 km al suroeste del volcán Petacas, en su zona de influencia se ubican los municipios La Cruz, San Pablo, Las Mesas, La Unión, Colón, San Bernardo (Nariño), y Florencia, Bolívar y Santa Rosa (Cauca)' WHERE "Name" = 'Volcán Las Ánimas';

-- Id 13 · Volcán Nevado de Santa Isabel
UPDATE "Volcano" SET "Description" = 'El volcán nevado de Santa Isabel, se encuentra localizado en los límites de los departamentos de Risaralda, Caldas y Tolima, en las coordenadas geográficas 4° 47'' N y 75° 24'' O, a una distancia de 140 km al noreste de Bogotá y a 33 km al sureste de Manizales. El acceso al volcán se realiza por la carretera Manizales - Murillo, tomando el mismo desvío que hacia el Ruiz, en Brisas, hasta la altura de La Olleta; de allí se desvía hacia el sur (derecha), hasta la Hacienda Potosí; luego se hace otro tramo por un carreteable sólo utilizable en verano y a pie hacia el volcán. También, se puede acceder al Nevado de Santa Isabel utilizando la carretera y camino que, desde Pereira, llevan a la Laguna del Otún. El Complejo de Domos del Santa Isabel fue construido sobre un basamento metamórfico del Paleozoico y de rocas vulcano-sedimentarias del Mesozoico, intruido por el Batolito de El Bosque de edad terciaria; se encuentra sobre la falla de Palestina, en sitios de intersección con fallas transversales. En el complejo dómico han sido determinados antiguos flujos de lava de composición andesítica de dos piroxenos y unas más recientes que las suprayacen (flujos de lava en bloques, provenientes principalmente de los domos actuales), también de composición andesítica. Adicionalmente, han sido identificados tres domos, denominados Norte, Centro y Sur, a los cuales se les puede agregar otros cuatro, ubicados al S del edificio principal, llamados Alsacia Norte, Alsacia Sur, Arenero Norte y Arenero Sur. También, en las partes somitales han sido encontrados, debajo de los flujos de lava originados en los domos actuales, principalmente del domo Norte, depósitos de flujos piroclásticos de ceniza y bloques, de escoria y de ceniza y pómez.' WHERE "Name" = 'Volcán Nevado de Santa Isabel';

-- Id 14 · Volcán Nevado del Huila
UPDATE "Volcano" SET "Description" = 'El Complejo Volcánico Nevado del Huila (CVNH) conocido comúnmente como el Volcán Nevado del Huila, hace parte del Parque Nacional Natural del mismo nombre que está localizado entre los departamentos de Cauca, Huila y Tolima, en las coordenadas 2° 55'' N y 76° 03'' W a una distancia de 285 km al SW de Bogotá, 85 km al NE de Popayán y 60 km al WSW de Neiva. Su altura máxima, el Pico Central (5 364 m s.n.m.), corresponde al punto más alto de la cordillera Central y de los Andes en Colombia. El Volcán Nevado del Huila es un complejo volcánico activo conformado por estratovolcanes y varios domos (en el Pico Sur). Su actividad ha sido dominantemente efusiva, pero en su desarrollo más reciente ha generado flujos piroclásticos producidos por colapsos y/o explosiones de domos. El Complejo Volcánico se ha formado a través de dos edificios sobrepuestos, llamados Pre-Huila y Huila. Este último se desarrolló en dos etapas: Edificio Antiguo y Edificio Actual. Los productos emitidos por este Complejo Volcánico han sido principalmente de composición andesítica. El basamento de este Complejo Volcánico está conformado por rocas de diferente litología y edad, entre las que se destacan rocas metamórficas del Precámbrico (Neis de Quintero) y del Paleozoico (esquistos del Complejo Cajamarca), rocas plutónicas del Jurásico (cuarzodioritas y granodioritas del Batolito de La Plata, que conforman cerca del 60% del basamento) y rocas metasedimentarias del Cretácico (pizarras, filitas y meta-areniscas). Sobre este basamento cruzan fallas con dirección general NNE, entre las que se encuentran las de Moras Oeste, Moras Este, Símbola, Inzá y Tálaga, y otras orientadas más hacia el NE, como las de Tóez y Calambayú.' WHERE "Name" = 'Volcán Nevado del Huila';

-- Id 17 · Volcán Paramillo de Santa Rosa
UPDATE "Volcano" SET "Description" = 'El VPSR es el más occidental de los volcanes del Complejo Volcánico Cerro Bravo-Cerro Machín (CVCBCM) y está desplazado unos 10 km hacia el occidente con respecto al eje de la Cordillera Volcánica Central, hallándose en correspondencia con la Laguna del Otún y la parte meridional del Nevado Santa Isabel. Para llegar al paramillo se puede tomar la vía que desde el municipio de Santa Rosa de Cabal conduce hasta el sitio, tras recorrer aproximadamente 8 km en dirección suroriental. El basamento sobre el cual se levanta este estratovolcán, el cual cubre una zona de 160 km², está constituido por el Complejo Metamórfico Paleozoico del Cajamarca. Sus lavas, de naturaleza porfirítica andesítica, se caracterizan por una abundante cantidad de plagioclasa zonada (An43-39), augita, hiperstena, hornblenda parda y óxidos opacos en una matriz intersertal hialina. La parte superior de la estructura está disectada por diques, y presenta una marcada alteración hidrotermal.' WHERE "Name" = 'Volcán Paramillo de Santa Rosa';

-- Id 21 · Volcán Romeral
UPDATE "Volcano" SET "Description" = 'El Volcán Romeral está ubicado en la zona central de Colombia en el departamento de Caldas, el acceso se puede realizar por vía carreteable que comunica a los municipios de Neira y Marulanda. Corresponde a una geoforma de forma cónica de base amplia con un patrón de drenaje dendrítico de baja densidad de dispersión radial, donde nacen cuatro cuencas hidrográficas correspondientes a los ríos Chamberí, Tapias y Guacaíca los cuales drenan sus aguas hacia el departamento de Caldas y el río Guarinó hacia el departamento del Tolima.' WHERE "Name" = 'Volcán Romeral';

-- Id 22 · Volcán San Diego
UPDATE "Volcano" SET "Description" = 'San Diego es un volcán conformado por una caldera (Laguna de San Diego) y un cono de tipo estratovolcán, Morro de San Diego, construido al NE del margen de la caldera. Una de las características principales de la laguna es la presencia de aguas termales, que hacen que la temperatura del agua sea aproximadamente 30 °C en el centro de ésta y se incremente hacia el norte de la misma. Esporádicamente se observan emisiones gaseosas. Ha sido catalogado geomorfológicamente como el Maar de San Diego, cuyo cráter tiene aproximadamente 3 km de diámetro y está cortado por fallas Norte-Sur, pertenecientes al sistema de fallas de Palestina (Feininger, 1970). En él se localiza una laguna que tiene aproximadamente 250 m bajo el borde del cráter con una profundidad de más de 60 m en el centro de la misma. El cono volcánico de San Diego tiene una altitud de 1150 m, es decir, 450 m por encima del lago. Este cono tiene una pequeña colina hacia el norte, la cual se encuentra recubierta por depósitos piroclásticos y al parecer están aislados del lago por un lineamiento NO, que divide en dos el límite del evento volcánico. Hacia la parte NE se encuentra el cono de San Diego y el pequeño cono adventicio en la parte sur del lago. Entre sus productos principales se tienen los depósitos de una erupción freatomagmática datada en 18.700 ± 10.000 años que se caracterizan por la abundancia de material lítico, además de la presencia de pómez y cristales (Toro, 1989).' WHERE "Name" = 'Volcán San Diego';

-- Id 24 · Volcán Sucubún
UPDATE "Volcano" SET "Description" = 'El volcán Sucubún está localizado entre los departamentos de Cauca y Huila, en las coordenadas 2° 01'' N y 76° 34'' W a una distancia de 400 km al SW de Bogotá y 47 km al SE de Popayán, su máxima altura es de 4100 m s.n.m.. La población más cercana es Guachicono Frío (resguardo indígena), localizado a 11 km al W del volcán Sucubún. Otras poblaciones en los alrededores del volcán son Río Blanco (Cauca) a 13 km al NW, Paispamba (Cauca) a 26 km al NNW, Paletará (Cauca) a 23 km NE, San Agustín (Huila) a 37 km SE y Puerto Quinchana (Huila) a 20 km al SE. El volcán Sucubún se ubica en el suroccidente colombiano, sobre la Cordillera Central. Su máxima altitud es de 4100 m s.n.m. Se encuentra a 10 km al SSE del volcán Sotará. Este volcán, en su expresión joven presenta una forma dómica de 2,1 km de diámetro y se encuentra en el interior de los remanentes de dos estructuras volcánicas concéntricas más antiguas, que conformaban una antigua caldera externa y un cono destruido. De acuerdo con trabajos geológicos preliminares de campo, así como con el apoyo de sensores remotos, ambos realizados por el SGC (Pulgarín et al., 2010), a estas estructuras volcánicas se le asocian depósitos de flujos de lava, potentes y extensas corrientes de densidad piroclástica concentradas y diluidas intercaladas con caídas piroclásticas, domos de lava y algunos lahares.' WHERE "Name" = 'Volcán Sucubún';

COMMIT;
