name: Build and test - ApiColombia

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api.Tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test --no-build --configuration Release --settings ./coverlet.runsettings --collect:"XPlat Code Coverage" --logger trx --results-directory ../TestResults /p:CollectCoverage=true /p:CoverletOutput=../TestResults/coverage/ /p:CoverletOutputFormat=cobertura
      
      - name: Verify coverage file exists
        working-directory: ./
        run: |
          echo "Current directory: $(pwd)"
          echo "Looking for coverage file at: $(pwd)/TestResults/coverage/coverage.cobertura.xml"
          ls -la TestResults/coverage/ || echo "Directory listing failed"
          [ -f TestResults/coverage/coverage.cobertura.xml ] || (echo "##[error]Coverage file not found in $(pwd)/TestResults/coverage/" && exit 1)
      
      - name: Generate HTML report
        working-directory: ./
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.10
          reportgenerator \
            -reports:TestResults/coverage/coverage.cobertura.xml \
            -targetdir:CoverageReport \
            -reporttypes:HtmlInline_AzurePipelines

      - name: Extract coverage percentage
        working-directory: ./
        id: coverage
        run: |
          # Extract coverage percentage from the cobertura.xml file
          COVERAGE=$(grep -oP 'line-rate="\K[0-9.]+' TestResults/coverage/coverage.cobertura.xml)
          COVERAGE_PERCENT=$(echo "$COVERAGE * 100" | bc -l | awk '{printf "%.0f\n", $1}')
          echo "coverage_percentage=$COVERAGE_PERCENT" >> $GITHUB_OUTPUT
          echo "Coverage: $COVERAGE_PERCENT%"

      - name: Create coverage badge
        working-directory: ./
        run: |
          echo '{"schemaVersion": 1, "label": "coverage", "message": "${{ steps.coverage.outputs.coverage_percentage }}%", "color": "success"}' > coverage.json
      
      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.json      

      - name: Publish coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: CoverageReport

      - name: Publish test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults